# Generated by Django 3.1.7 on 2021-03-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='work priority'),
        ),
    ]
